server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  application:
    name: user-service

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root123root123
#spring.datasource.url=jdbc:mysql://localhost:3306/demo?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#
#spring.jpa.database=mysql
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#feign:
#  client:
#    config:
#      order-service:
#        loggerLevel:full
feign:
  httpclient:
    enabled: true
    max-connections: 200
#spring.jpa.jpashow-sql=true
